services:
  # Mysql database container
  db:
    image: mysql
    container_name: tutorial_db_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - tutorial
  # Symfony apache project container
  www:
    build: php
    container_name: tutorial_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - tutorial

networks:
  tutorial:

volumes:
  db-data: